alexkrechik.cucumberautocomplete
angular.ng-template
anthropic.claude-code
arcanis.vscode-zipfs
arjun.swagger-viewer
asvetliakov.vscode-neovim
bierner.markdown-mermaid
bpruitt-goddard.mermaid-markdown-syntax-highlighting
christian-kohler.npm-intellisense
continue.continue
darkriszty.markdown-table-prettify
davidanson.vscode-markdownlint
dbaeumer.vscode-eslint
docker.docker
donjayamanne.githistory
dotjoshjohnson.xml
eamodio.gitlens
editorconfig.editorconfig
foam.foam-vscode
formulahendry.docker-explorer
foxundermoon.shell-format
github.copilot
github.copilot-chat
github.vscode-github-actions
golang.go
google.gemini-cli-vscode-ide-companion
google.geminicodeassist
harness-inc.oss-gitspaces
hashicorp.terraform
ibm.output-colorizer
ipedrazas.kubernetes-snippets
jgclark.vscode-todo-highlight
kilocode.kilo-code
mikestead.dotenv
ms-azuretools.vscode-containers
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.debugpy
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-python.vscode-python-envs
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-powertoys
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.js-debug-nightly
ms-vscode.makefile-tools
ms-vscode.remote-explorer
oven.bun-vscode
pkief.material-icon-theme
redhat.java
redhat.vscode-yaml
robertarles.notekeep-vscode
rooveterinaryinc.roo-cline
rust-lang.rust-analyzer
shd101wyy.markdown-preview-enhanced
tamasfe.even-better-toml
tauri-apps.tauri-vscode
timonwong.shellcheck
tintinweb.graphviz-interactive-preview
vadimcn.vscode-lldb
vmware.vscode-boot-dev-pack
vmware.vscode-spring-boot
vscjava.vscode-gradle
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscjava.vscode-spring-boot-dashboard
vscjava.vscode-spring-initializr
vspacecode.whichkey
xaver.clang-format
yzhang.markdown-all-in-one
